color = input('Input a color: ')
flower_name = input('Input a flower (in plural): ')
celebrity = input('Input a celebrity: ')
print(f'Roses are {color}')
print(f'{flower_name} are blue')
print(f'I love {celebrity}')